Traceback (most recent call last):
  File "C:\Users\edier\miniconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\edier\miniconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\edier\miniconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\edier\miniconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\edier\miniconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\edier\miniconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\edier\miniconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\edier\miniconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np

A=([[1, 0.33,  0.33,  1, 0.33, 0.33],
    [3,    1,  0.33,  5,    1,    1],
    [3,    3,     1,  3,    1,    1],
    [1,  0.2,  0.33,  1,    1,  0.2],
    [3,    1,     1,  1,    1, 0.33],
    [3,    1,     1,  5,    3,    1]])

B=np.array(A) # para transformarla en una matriz

values, vectores=np.linalg.eig(B) # FunciÃ³n para calcular los valores y vectores propios

vector_norm=vectores/np.linalg.norm(vectores, ord=1) # normalizaciÃ³n de los vectores

print('esto son los valores propios',values)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn [1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m      3[0m A[38;5;241m=[39m([[[38;5;241m1[39m, [38;5;241m0.33[39m,  [38;5;241m0.33[39m,  [38;5;241m1[39m, [38;5;241m0.33[39m, [38;5;241m0.33[39m],
[0;32m      4[0m     [[38;5;241m3[39m,    [38;5;241m1[39m,  [38;5;241m0.33[39m,  [38;5;241m5[39m,    [38;5;241m1[39m,    [38;5;241m1[39m],
[0;32m      5[0m     [[38;5;241m3[39m,    [38;5;241m3[39m,     [38;5;241m1[39m,  [38;5;241m3[39m,    [38;5;241m1[39m,    [38;5;241m1[39m],
[0;32m      6[0m     [[38;5;241m1[39m,  [38;5;241m0.2[39m,  [38;5;241m0.33[39m,  [38;5;241m1[39m,    [38;5;241m1[39m,  [38;5;241m0.2[39m],
[0;32m      7[0m     [[38;5;241m3[39m,    [38;5;241m1[39m,     [38;5;241m1[39m,  [38;5;241m1[39m,    [38;5;241m1[39m, [38;5;241m0.33[39m],
[0;32m      8[0m     [[38;5;241m3[39m,    [38;5;241m1[39m,     [38;5;241m1[39m,  [38;5;241m5[39m,    [38;5;241m3[39m,    [38;5;241m1[39m]])
[0;32m     10[0m B[38;5;241m=[39mnp[38;5;241m.[39marray(A) [38;5;66;03m# para transformarla en una matriz[39;00m

[1;31mModuleNotFoundError[0m: No module named 'numpy'
ModuleNotFoundError: No module named 'numpy'

