Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Python39\lib\site-packages\nbclient\client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Python39\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Python39\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Python39\lib\site-packages\nbclient\client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "C:\Python39\lib\site-packages\nbclient\client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Python39\lib\site-packages\nbclient\client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Para utilizar validacion cruzada con el 80/20%
x_train,x_validation,y_train,y_validation=model_selection.train_test_split(x1, y, test_size=0.2, random_state=7)
print('Tama√±o de variables de entrenamiento:', x_train.shape)
print('Tama√±o de labels de entrenamiento:', y_train.shape)
print('Tama√±o de variables de validaci√≥n:', x_validation.shape)
print('Tama√±o de labels de validaci√≥n:', y_validation.shape)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_4588/2042219194.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m#Para utilizar validacion cruzada con el 80/20%[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mx_train[0m[1;33m,[0m[0mx_validation[0m[1;33m,[0m[0my_train[0m[1;33m,[0m[0my_validation[0m[1;33m=[0m[0mmodel_selection[0m[1;33m.[0m[0mtrain_test_split[0m[1;33m([0m[0mx1[0m[1;33m,[0m [0my[0m[1;33m,[0m [0mtest_size[0m[1;33m=[0m[1;36m0.2[0m[1;33m,[0m [0mrandom_state[0m[1;33m=[0m[1;36m7[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0mprint[0m[1;33m([0m[1;34m'Tama√±o de variables de entrenamiento:'[0m[1;33m,[0m [0mx_train[0m[1;33m.[0m[0mshape[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mprint[0m[1;33m([0m[1;34m'Tama√±o de labels de entrenamiento:'[0m[1;33m,[0m [0my_train[0m[1;33m.[0m[0mshape[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0mprint[0m[1;33m([0m[1;34m'Tama√±o de variables de validaci√≥n:'[0m[1;33m,[0m [0mx_validation[0m[1;33m.[0m[0mshape[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'model_selection' is not defined
NameError: name 'model_selection' is not defined

